### ISSUE TITLE
Implement `rdcycle`, `rdtime`, and `rdinstret` 

### ISSUE THREAD

**Issue by fabianpedd** [tum-ei-eda/etiss#105]
Would be nice if ETISS supported these (OVPsim and Spike offer them). Currently reading them returns 0. 

See `RISC-V User-Level ISA V2.2, 2.8 Control and Status Register Instructions, Timers and Counters` for more info. They can then in turn be used to, for example, run performance tests on TensorFlow Lite Micro.

**Comment by wysiwyng** [comment]
@samanti-das and me will have a go at implementing this, stay tuned.

**Comment by wysiwyng** [comment]
Implemeted in #115. `rdtime` currently returns microseconds since Unix epoch, `rdcycle` and `rdinstret` return instruction count since simulator start.
