### ISSUE TITLE
CPU bootup

### ISSUE THREAD

**Issue by uzleosharif** [tum-ei-eda/etiss#11]
Currently in both the 32/64 bit versions of RISCVArch implementations, we are forced to boot from 0x80 which might not be true for general RISCV SoCs, though compatible with Pulpino. We have to provide flexibility and remove this hardcoded impl.

Moreover it also seems that **RISCArch::resetCPU(... cpu, ... startpointer)** doesn't really respect the custom passed startpointer b/c the HW reset at the start of the simulation basically override this setting

**Comment by uzleosharif** [comment]
just checked the reset interface is also not working for other targets as well so more accurately it is an ETISS issue with nothing specific to RISCV

**Comment by rafzi** [comment]
the entry point is now chosen based on the loaded ELF file
