### ISSUE TITLE
CI: Broken after removing 'examples/'  8f2fb89

### ISSUE THREAD

**Issue by JoGei** [tum-ei-eda/etiss#148]
After commit 8f2fb89 removed the `examples/` CI was not updated and fails.

**Comment by jokap11** [comment]
Do you think this is a suitable solution? https://github.com/tum-ei-eda/etiss/pull/138/commits/0b8ad8ad0158062950a813b8b1485b77b1894e93 
Removing all example parts?
Or should the CI file load the submodule?

**Comment by PhilippvK** [comment]
The etiss riscv tests moved to https://github.com/tum-ei-eda/etiss_riscv_examples.

(@wysiwyng)

To fix the CI in the `etiss` repo we could:
1. Drop the CI jobs all together (not recommended)
2. Build new CI jobs in this repository based on `etiss_riscv_examples`.
3. Add CI to `etiss_riscv_examples` repository and trigger it from the `etiss` repo (if feasible)

**Comment by JoGei** [comment]
> Do you think this is a suitable solution? [0b8ad8a](https://github.com/tum-ei-eda/etiss/commit/0b8ad8ad0158062950a813b8b1485b77b1894e93) Removing all example parts? Or should the CI file load the submodule?

No, not really. I think the examples and the CI tests were quite helpful as a form of "sanity tests". So I would try to keep them.

**Comment by wysiwyng** [comment]
I also think 2.b) is the best option, I am rewriting the ci file. We could also add https://github.com/tum-ei-eda/etiss_riscv_tests here to have actual functional tests. These should then only report the status, not fail the CI when tests don't pass.
