### ISSUE TITLE
RISCVArch xIE CSRs (implementation specific fields) not setable

### ISSUE THREAD

**Issue by JoGei** [tum-ei-eda/etiss#29]
When trying to enable implementation specific lines in the Interrupt enable registers, bits above 12 are ignored by CSR Write instructions.
https://github.com/riscv/riscv-isa-manual/releases/download/Ratified-IMFDQC-and-Priv-v1.11/riscv-privileged-20190608.pdf

specifies at p. 31 to enable bits 16 on-wards as custom interrupt lines which seem to be ignored by ETISS. 

Test code:

```
int main()
{
    unsigned int tmie, t_smie = 0xFFFFFFFF;

    asm volatile("csrr %[rd], 0x304" : [rd] "=r" (tmie) );

    printf("MIE after reset: %x\n", tmie);

    asm volatile ("csrw 0x304, %0" : /* no output */ : "r" (t_smie));

    asm volatile("csrr %[rd], 0x304" : [rd] "=r" (tmie) );

    printf("MIE after attempted set: %x\n", tmie);
}

```

reports:

=== Setting up configurations ===
  Load ini file.
  Load Configs from .ini files:
ETISS: Info: Created new config container: global
ETISS: Info:   [BoolConfigurations]
ETISS: Info:     cleanup=true,
ETISS: Info:     copy-headers=true,
ETISS: Info:     ETISS::enable_dmi=true,
ETISS: Info:     ETISS::log_pc=false,
ETISS: Info:     hostendianness=false,
ETISS: Info:     ignore_sr_iee=false,
ETISS: Info:     integrated-library=true,
ETISS: Info:     jit-debug=true,
ETISS: Info:     library-loading=true,
ETISS: Info:     norangeexception=false,
ETISS: Info:     pyconsole=false,
ETISS: Info:     returnjump=false,
ETISS: Info:     sigint-console=false,
ETISS: Info:     verifyJIT=false,
ETISS: Info:   [IntConfigurations]
ETISS: Info:     Arch::cpuCycleTime_ps=10000,
ETISS: Info:     ETISS::CPU_quantum_ps=100000,
ETISS: Info:     ETISS::sim_mode=0,
ETISS: Info:     ETISS::write_pc_trace_from_time_us=0,
ETISS: Info:     ETISS::write_pc_trace_until_time_us=3000000,
ETISS: Info:     ifStallCycles=0,
ETISS: Info:     logLevel=4,
ETISS: Info:     Translation::MaxBlockSize=100,
ETISS: Info:     vp::simulation_time_us=20000000,
ETISS: Info:   [StringConfigurations]
ETISS: Info:     CPUArch=RISCV,
ETISS: Info:     ETISS::outputPathPrefix=,
ETISS: Info:     sw_binary_ram=/data/home.local/repos/dumpy/etiss.du/build/installed/examples/SW/riscv/build/riscv_example.ram,
ETISS: Info:     sw_binary_rom=/data/home.local/repos/dumpy/etiss.du/build/installed/examples/SW/riscv/build/riscv_example.rom,
ETISS: Info:     vp::dram_file=/data/home.local/repos/dumpy/etiss.du/build/installed/examples/SW/riscv/build/riscv_example.ram,
ETISS: Info:     vp::iram_file=/data/home.local/repos/dumpy/etiss.du/build/installed/examples/SW/riscv/build/riscv_example.rom,
=== Finished setting up configurations ===

=== Setting up test system ===
  Setting up Memory
rom binary loaded!
ram binary loaded!
  Setting up CPUCore
=== Finished Setting up test system ===

=== Setting up plug-ins ===
ETISS: Info:   Adding Plugin Logger
ETISS: Info:     options[logaddr] = 0x80000000
ETISS: Info:     options[logmask] = 0x80000000
ETISS: Info: Plugin "Logger" loaded via library interface "ETISSINCLUDED"
ETISS: Info:  Adding JIT "TCCJIT"
=== Setting up plug-ins ===

=== Simulation start ===
ETISS: Info: Init Plugin Logger @2147483648{SYSTEMWRAPPER}
ETISS: Warning: Removed empty etiss::instr::InstructionSet during compilation. 
	{
		{ISA64_RISCV}
	}
ETISS: Warning: Removed empty etiss::instr::InstructionSet during compilation. 
	{
		{ISA64_RISCV}
	}
MIE after reset: 0
MIE after attempted set: bbb
CPU Time: 0.000138031s    Simulation Time: 0.2609s
CPU Cycles (estimated): 4417
MIPS (estimated): 0.0169299
=== Simulation end ===

CPU0 exited with exception: 0x80000000: Finished cpu execution. This is the proper way to exit from etiss::CPUCore::execute._

**Comment by DanMueGri** [comment]
Is solved with the new RISC-V architectures from CoreDSL2.
