### ISSUE TITLE
CI does not test LLVMJIT on Windows

### ISSUE THREAD

**Issue by rafzi** [tum-ei-eda/etiss#92]
The chocolatey package (and the official llvm installer) do not provide the required cmake files for `FIND_PACKAGE`.

See https://groups.google.com/g/llvm-dev/c/BT3fCvN6DCk

The solutions do not seem great:

- Build LLVM from source. Not really feasable in the CI, have to prepare some package or look for a prebuilt one.
- Manually include the libs and headers without `FIND_PACKAGE`

**Comment by DanMueGri** [comment]
Closed, native windows support to WSL, so no native windows support required anymore.
