### ISSUE TITLE
Benchmarking: Pull request comments cannot be added

### ISSUE THREAD

**Issue by wysiwyng** [tum-ei-eda/etiss#97]
See e.g. https://github.com/tum-ei-eda/etiss/runs/3995739155?check_suite_focus=true#step:5:28 . The documentation of the GitHub action used to create comments says we need to add a private access token of an account with access to the repository for this to work (https://github.com/peter-evans/create-or-update-comment#accessing-issues-and-comments-in-other-repositories) This means either a developer has to supply their PAT to this repo, or we need a service account which is only used for activities such as these.

**Comment by wysiwyng** [comment]
As I read the documentation of that action, I think the two options for the two steps should be okay, especially because this logic works when tested in a private repo. From this document: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks I get the feeling that this we are experiencing exactly this error (PR from a forked repo).

**Comment by rafzi** [comment]
Alright, reading it again I understand the issue now. When a PR is submitted from a fork, the CI does not have sufficient permissions to write comments. So it seems like we have to disable this feature for now. Maybe an approach with an extra action that is triggered by the CI completion is possible? Similar to: https://stackoverflow.com/a/64126737 , but triggered on CI completion if possible. Then that action could copy the results from the results branch of the fork to a comment.

**Comment by rafzi** [comment]
something like this could work: 

```
on:
  workflow_run:
    workflows: ["compare_mips"]
    types:
      - completed

jobs:
  comment:
    steps:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
```
